"""Pure runtime-layer models for local arena session orchestration."""

from arena.runtime.exceptions import (
    ArenaRuntimeError,
    InvalidMatchId,
    InvalidPlayerRecord,
    RuntimeAbortedError,
    RuntimeStateError,
)
from arena.runtime.formatting import (
    format_runtime_session_report,
    format_runtime_transcript,
    format_session_status,
)
from arena.runtime.ids import MatchId, generate_match_id
from arena.runtime.models import (
    AbortMetadata,
    AbortReason,
    MatchAborted,
    MatchCreated,
    MatchFinished,
    MatchStarted,
    PlayerRecord,
    PolicyDecided,
    PolicyRetried,
    RuntimeEvent,
    RuntimeLifecycle,
    TurnAccepted,
    TurnRequested,
)
from arena.runtime.payloads import (
    RUNTIME_STATUS_SCHEMA_VERSION,
    RUNTIME_TRANSCRIPT_SCHEMA_VERSION,
    RuntimeAbortPayload,
    RuntimeEventPayload,
    RuntimePlayerPayload,
    RuntimeResultPayload,
    RuntimeSessionStatusPayload,
    RuntimeTranscriptPayload,
    dump_runtime_transcript,
    dump_session_status,
    validate_runtime_transcript,
    validate_session_status,
)
from arena.runtime.session import Arena, MatchSession, record_runtime_event

__all__ = [
    "AbortMetadata",
    "AbortReason",
    "Arena",
    "ArenaRuntimeError",
    "InvalidMatchId",
    "InvalidPlayerRecord",
    "MatchAborted",
    "MatchCreated",
    "MatchFinished",
    "MatchId",
    "MatchSession",
    "MatchStarted",
    "PlayerRecord",
    "PolicyDecided",
    "PolicyRetried",
    "RUNTIME_STATUS_SCHEMA_VERSION",
    "RUNTIME_TRANSCRIPT_SCHEMA_VERSION",
    "RuntimeAbortPayload",
    "RuntimeAbortedError",
    "RuntimeEventPayload",
    "RuntimeEvent",
    "RuntimeLifecycle",
    "RuntimePlayerPayload",
    "RuntimeResultPayload",
    "RuntimeSessionStatusPayload",
    "RuntimeStateError",
    "RuntimeTranscriptPayload",
    "TurnAccepted",
    "TurnRequested",
    "dump_runtime_transcript",
    "dump_session_status",
    "format_runtime_session_report",
    "format_runtime_transcript",
    "format_session_status",
    "generate_match_id",
    "record_runtime_event",
    "validate_session_status",
    "validate_runtime_transcript",
]
